version: "3.8"
services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/db
      NODE_ENV: development
      PORT: 3000
    ports:
      - "5173:3000"
    networks:
      - pern-app
  postgres:
    image: postgres:13
    ports:
      - "35000:5432"
    networks:
      - pern-app
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - pern-app
    volumes:
      - postgres-data:/data/db
networks:
  pern-app:
    driver: bridge
volumes:
  postgres-data:
    driver: local
